### ISSUE TITLE
Switch to using output files to map URLs

### ISSUE THREAD

**Issue by dominicbarnes** [makojs/serve#30]
I really need to figure out definitively how to map URLs to files in the dependency/build trees. Currently, I'm relying on the entry files, as opposed to the output files. This approach was really easy to implement, but it breaks down when `file.type` changes during the parse. (eg: `.md` -> `.html`, `.ts` -> `.js`)

The difficulty in simply switching to the output files is that determining the root to resolve from is a moving target. (this may not be a real issue, since `Tree#findFile` searches all the paths a file has taken during it's lifetime) In addition, there's a bit of a chicken/egg problem, since you need to run a build in order to know what the output files were in the first place. (but in the name of efficiency, it'd be nice to avoid building files that are never requested)

**Comment by dominicbarnes** [comment]
Another issue to resolve is another chicken/egg problem, which is how to know when to trigger a build. Now, I'm relying on the input file being in the list of `config.entries`, but this breaks down as well.

Maybe the "on-demand" building is just not the right approach. Perhaps it's time to figure out how to incorporate a watcher to be more efficient here, or perhaps just rebuild at intervals.

I'm getting tempted to pull more logic into core, such as stat/watch and output... but I'm really wanting to avoid having core be so tightly-coupled. I'll continue mulling over different ideas, there has to be a good solution.

**Comment by dominicbarnes** [comment]
The next version will serve output files directly, solving this problem.

**Comment by matthewmueller** [comment]
yep, i think that's the right approach, build first then, if there's an error display an error page (like budo), if not use the output build tree to serve the files. `.html` files are a bit tricky, but simple heuristics solve most usecases.
